"""initial_schema_with_refactor_models

Revision ID: d59d2a92a78e
Revises: 
Create Date: 2026-05-14 13:27:43.851736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59d2a92a78e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_checkpoints_session_id'), 'discussion_checkpoints', ['session_id'], unique=False)
    op.create_index(op.f('ix_discussion_checkpoints_thread_id'), 'discussion_checkpoints', ['thread_id'], unique=True)
    op.create_table('script_vectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chroma_doc_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_vectors_chroma_doc_id'), 'script_vectors', ['chroma_doc_id'], unique=True)
    op.create_index(op.f('ix_script_vectors_project_id'), 'script_vectors', ['project_id'], unique=False)
    op.create_index(op.f('ix_script_vectors_user_id'), 'script_vectors', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('preference_key', sa.String(length=255), nullable=False),
    sa.Column('preference_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_script_vectors_user_id'), table_name='script_vectors')
    op.drop_index(op.f('ix_script_vectors_project_id'), table_name='script_vectors')
    op.drop_index(op.f('ix_script_vectors_chroma_doc_id'), table_name='script_vectors')
    op.drop_table('script_vectors')
    op.drop_index(op.f('ix_discussion_checkpoints_thread_id'), table_name='discussion_checkpoints')
    op.drop_index(op.f('ix_discussion_checkpoints_session_id'), table_name='discussion_checkpoints')
    op.drop_table('discussion_checkpoints')
    # ### end Alembic commands ###
